# -*- coding: utf-8 -*-
"""Location.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4cZ65pUYxXrEn9qTrAkV4-mLpAdgP9t
"""

import pandas as pd
import requests
import json
import io

from google.colab import files

uploaded = files.upload()

df = pd.read_csv(io.StringIO(uploaded['Postcode_1.csv'].decode('utf-8'))) #change the name of the file whenever uploading new file

codes = df['PostCode'].tolist()

url = "https://api.company-information.service.gov.uk/advanced-search/companies?location={}&company_status=active&size=500"
api_key = "ce1a8b4d-fd6c-49f3-9c10-a243816c2b05"

errors = []
master=[]
for code in codes:
    try:
        response=requests.get(url.format(code),auth=(api_key,''))
        data=json.loads(response.text)
        for item in data['items']:
            master.append(
                {
                    'count':data['hits'],
                    'Postcode':code,
                    'Company_Name':item['company_name'],
                    'Registered_Office_Address':item['registered_office_address']
                })
    except Exception:
      errors.append({'NoCompany_Posdcode':code})

Finaldf=pd.DataFrame(master)
Finaldf
Finaldf.to_csv('Location_1.csv') #change the name file as per your preference
files.download('Location_1.csv')

Errordf=pd.DataFrame(errors)
Errordf.to_csv('NoCompany_1.csv') #change the name file as per your preference
files.download('NoCompany_1.csv')